apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: go-sample
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: go-sample
    app.kubernetes.io/part-of: july-app
  name: go-sample
  namespace: rhn-support-tshearon
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: go-sample
status:
  loadBalancer: {}
